# Benefits of using tox:
#
# 1. makes sure we are testing gordion as installed by setup.py
# 2. avoid touching user global / system config files
# 3. avoid touching any git repositories outside of tmpdirs
# 4. ensure global / system config settings have no effect on the tests

[tox]
envlist=py3

[flake8]
# ignore = E#

max-line-length = 100
indent-size = 2

[mypy]
mypy_path=src
ignore_missing_imports=True

[testenv]
deps =
    pytest
    pytest-cov
    types-PyYAML
    flake8
    mypy
    debugpy
setenv =
    TOXTEMPDIR={envtmpdir}
commands =
  python -m pytest --cov=gordion {posargs:tests}
  python -m flake8 --config={toxinidir}/tox.ini {toxinidir}
  python -m mypy --config-file={toxinidir}/tox.ini --package=gordion
