# Benefits of using tox:
#
# 1. makes sure we are testing gordion as installed by setup.py
# 2. avoid touching user global / system config files
# 3. avoid touching any git repositories outside of tmpdirs
# 4. ensure global / system config settings have no effect on the tests

[tox]
envlist = unit, lint

[flake8]
ignore = E126
exclude = setup.py,.tox,build
max-line-length = 100
indent-size = 2

[mypy]
mypy_path=src
ignore_missing_imports=True

# Unit tests
[testenv:unit]
deps =
    pytest
    pytest-cov
    gitpython==3.1.43
    types-PyYAML
    debugpy
    pytest
    pyYAML
setenv =
    TOXTEMPDIR={envtmpdir}
commands =
    python -m pytest --cov=gordion {posargs:tests}

# Linting and type checking
[testenv:lint]
deps =
    flake8
    mypy
    types-PyYAML
commands =
    python -m flake8 --config={toxinidir}/tox.ini {toxinidir}
    python -m mypy --config-file={toxinidir}/tox.ini --package=gordion

